---
# List previous backups

- assert: 
    that: backup_dir is defined
- stat: path={{backup_dir}} get_checksum=false get_md5=false
  register: backup_dir_stat
- name: Check if backup dir exist
  assert:
    that: backup_dir_stat.stat.exists and backup_dir_stat.stat.isdir

- name: List previous backups
  shell: "cd {{backup_dir}};ls -dtr *"
  register: dirs
- debug: var=dirs.stdout_lines    
